name: Deploy PHP Site to Linode

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Linode server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 172.234.192.40 >> ~/.ssh/known_hosts

    - name: Sync files to Linode server
      run: |
        rsync -avz --delete \
          --exclude '.git*' \
          --exclude '.github' \
          ./ \
          d@d2fn.com:/var/www/d2fn.com/html

    - name: Restart Nginx (optional if needed)
      run: |
        ssh d@2fn.com "sudo systemctl restart nginx"

